theme: jekyll-theme-minimal
title: Luca Gazzola
layout: default
plugins:
    - jekyll-optional-front-matter
include:
    - README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: Software engineer in test @ lastminute.com
twitter:
    - username: gazzo87
social:
  name: Luca Gazzola
  links:
    - https://twitter.com/gazzo87
description: 
    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:luca.gazzola@lastminute.com">luca.gazzola@lastminute.com</a><br>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://www.twitter.com/gazzo87">@gazzo87</a><br>
    <i class="fa fa-facebook" aria-hidden="true"></i>
    <span class="sr-only">Facebook:</span>&nbsp;&nbsp;<a href="https://www.facebook.com/luca.gazzola2"> luca.gazzola2</a><br>
    <i class="fa fa-instagram" aria-hidden="true"></i>
    <span class="sr-only">Instagram:</span>&nbsp;&nbsp;<a href="https://www.instagram.com/luca.gazzola/">luca.gazzola</a><br>
    <i class="fa fa-linkedin" aria-hidden="true"></i>
    <span class="sr-only">LinkedIn:</span>&nbsp;&nbsp;<a href="https://www.linkedin.com/in/lucagazzola/">lucagazzola</a><br>
    <img src="/assets/scholar.png" width="20">
    <a href="https://scholar.google.com/citations?user=RRQby44AAAAJ&hl=en">Luca Gazzola</a>
logo: assets/me.png
