title: Luca Gazzola
tagline: Software engineer
description: Personal website of Luca Gazzola — software engineer with a background in software testing automation and academic research (PhD).
email: lgazzola87@gmail.com
url: https://lucagazzola.github.io
logo: /assets/me.jpg
permalink: /blog/:title/
author:
  name: Luca Gazzola
  twitter: gazzo87
social:
  twitter: https://twitter.com/gazzo87
  facebook: https://www.facebook.com/luca.gazzola2
  instagram: https://www.instagram.com/luca.gazzola/
  linkedin: https://www.linkedin.com/in/lucagazzola/
  scholar: https://scholar.google.com/citations?user=RRQby44AAAAJ&hl=en

plugins:
    - jekyll-optional-front-matter
include:
    - index.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
